export const SKILLS = [
    {
        title: "FrontEnd",
        icon:"./src/assets/images/frontend.png",   
        description: "I have experience in building responsive and interactive websites using HTML, CSS, and JavaScript.",
        Skills: [
            { Skill: "HTML5", percentage: "90%" },
            { Skill: "CSS3", percentage: "95%" },
            { Skill: "JavaScript", percentage: "85%" },
            { Skill: "React Js", percentage: "75%" },
            { Skill: "Bootstrap", percentage: "80%" },
            { Skill: "SASS", percentage: "70%" },
            { Skill: "Tailwind CSS", percentage: "60%" },
        ],
    },
    {
        title: "BackEnd",
        icon: "./src/assets/images/backend2.png",
        description: "I have experience in building RESTful APIs using Node.js, Express.js, and MongoDB.",
        Skills: [
            { Skill: "Node.js", percentage: "90%" },
            { Skill: "Express.js", percentage: "95%" },
            { Skill: "MongoDB", percentage: "85%" },
        ],
    },
    {
        title: "Tools",
        icon: "./src/assets/images/tools.png",
        description: "I have experience in using various tools and frameworks such as Git, GitHub, VS Code, and Postman.",
        Skills: [
            { Skill: "Git", percentage: "80%" },
            { Skill: "GitHub", percentage: "75%" },
            { Skill: "Webpack", percentage: "65%" },
            { Skill: "Responsive Design", percentage: "90%" },
        ],
    },
    {
        title: "Database",
        icon: "./src/assets/images/database.png",
        description: "I have experience in using NoSQL databases such as MongoDB and MySQL.",
        Skills: [
            { Skill: "MongoDB", percentage: "85%" },
            { Skill: "MySQL", percentage: "70%" },
            { Skill: "SQL", percentage: "80%" },
            { Skill: "NoSQL", percentage: "90%" },
            { Skill: "GraphQL", percentage: "60%" },
        ],
    },
    {
        title: "Soft Skills",
        icon: "./src/assets/images/softskills.png",
        description: "I have experience in working well in a team, adapting to new technologies, and problem-solving.",
        Skills: [
            { Skill: "Teamwork", percentage: "90%" },
            { Skill: "Adaptability", percentage: "85%" },
            { Skill: "Problem-Solving", percentage: "95%" },
            { Skill: "Leadership", percentage: "80%" },
            { Skill: "Communication", percentage: "90%" },
            { Skill: "Critical Thinking", percentage: "85%" },
            { Skill: "Empathy", percentage: "90%" },
            { Skill: "Patience", percentage: "80%" },
            { Skill: "Creativity", percentage: "95%" },
            { Skill: "Self-Management", percentage: "85%" },
            { Skill: "Time Management", percentage: "90%" },
            { Skill: "Resilience", percentage: "90%" },
            { Skill: "Innovation", percentage: "85%" },
            { Skill: "Public Speaking", percentage: "90%" },
            { Skill: "Conflict Resolution", percentage: "80%" },
            { Skill: "Project Management", percentage: "95%" },
            { Skill: "Creative Problem-Solving", percentage: "90%" },
            { Skill: "Technical Writing", percentage: "85%" },
            { Skill: "Networking", percentage: "95%" },
            { Skill: "Debating", percentage: "80%" },
            { Skill: "Negotiation", percentage: "90%" },
            { Skill: "Written Communication", percentage: "95%" },
            { Skill: "Oral Communication", percentage: "90%" },
        ],
    },
];
